docker run --name mc-postgres \
-e POSTGRES_DB=demo \
-e POSTGRES_USER=demo \
-e POSTGRES_PASSWORD=demo \
-p 5433:5432 \
-d postgres:16

==

docker run --name mc-postgres -e POSTGRES_DB=demo -e POSTGRES_USER=demo -e POSTGRES_PASSWORD=demo -p 5433:5432 -d postgres:16